name: Release

on:
    repository_dispatch:
        types: [auto-generate-release]

jobs:
    run-on-dispatch:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Read version
              id: read_version
              shell: bash
              run: |
                  echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT

            - name: Checkout Auto.dn repo
              uses: actions/checkout@v4
              with:
                  repository: AuTsing/Auto.dn
                  ref: refs/tags/v${{ steps.read_version.outputs.version }}
                  path: tmp/Autodn
                  token: ${{ secrets.DENOFA_TOKEN }}

            - name: Copy files
              run: |
                  cp tmp/Autodn/CHANGELOG.md ./CHANGELOG.md

            - name: Update readme
              run: |
                  sed -i "s/最新版本号: v.*/最新版本号: v${{ steps.read_version.outputs.version }}/" README.md

            - name: Commit changes
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add . || true
                  git commit -m "${{ steps.read_version.outputs.version }}" || true
                  git push || true
                  git tag -d "v${{ steps.read_version.outputs.version }}" || true
                  git tag "v${{ steps.read_version.outputs.version }}" || true
                  git push origin --delete "v${{ steps.read_version.outputs.version }}" || true
                  git push --tag || true

            - name: Read changelog
              id: read_changelog
              uses: mindsers/changelog-reader-action@v2
              with:
                  version: ${{ steps.read_version.outputs.version }}

            - name: Download release
              env:
                  GITHUB_TOKEN: ${{ secrets.DENOFA_TOKEN }}
              run: |
                  gh release download v${{ steps.read_version.outputs.version }} \
                    --repo AuTsing/Auto.dn \
                    --pattern "Denofa_v${{ steps.read_version.outputs.version }}_release.apk" \
                    --dir tmp

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: v${{ steps.read_version.outputs.version }}
                  draft: false
                  body: |
                      ## ${{ steps.read_changelog.outputs.version }} - ${{ steps.read_changelog.outputs.date }}

                      ${{ steps.read_changelog.outputs.changes }}
