name: Release

on:
    repository_dispatch:
        types: [auto-generate-release]

jobs:
    run-on-dispatch:
        runs-on: ubuntu-latest
        env:
            VERSION: ${{ github.event.client_payload.version }}
            TAG_NAME: v${{ github.event.client_payload.version }}
            DENOFA_TOKEN: ${{ secrets.DENOFA_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Checkout Auto.dn repo
              uses: actions/checkout@v4
              with:
                  repository: AuTsing/Auto.dn
                  ref: refs/tags/${{ env.TAG_NAME }}
                  path: tmp/Autodn
                  token: ${{ env.DENOFA_TOKEN }}

            - name: Download release
              id: download_release
              run: |
                  curl -H "Authorization: Bearer ${{ env.DENOFA_TOKEN }}" \
                      -H "Accept: application/vnd.github+json" \
                      https://api.github.com/repos/AuTsing/Auto.dn/releases/tags/${{ env.TAG_NAME }} \
                      > tmp/release.json
                  filename="Denofa_${{ env.TAG_NAME }}_release.apk"
                  asset_id=$(jq -r --arg FILENAME "$filename" '.assets[]? | select(.name==$FILENAME) | .id' tmp/release.json)
                  curl -L \
                      -H "Authorization: Bearer ${{ env.DENOFA_TOKEN }}" \
                      -H "Accept: application/octet-stream" \
                      https://api.github.com/repos/AuTsing/Auto.dn/releases/assets/$asset_id \
                      -o tmp/$filename
                  file_path=$(realpath tmp/$filename)
                  echo "file_path=${file_path}" >> $GITHUB_OUTPUT

            - name: Copy files
              run: |
                  cp tmp/Autodn/CHANGELOG.md ./CHANGELOG.md

            - name: Update readme
              run: |
                  sed -i "s/最新版本号: v.*/最新版本号: ${{ env.TAG_NAME }}/" README.md

            - name: Commit changes
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add . || true
                  git commit -m ${{ env.VERSION }} || true
                  git push || true
                  git tag -d "${{ env.TAG_NAME }}" || true
                  git tag "${{ env.TAG_NAME }}" || true
                  git push origin --delete "${{ env.TAG_NAME }}" || true
                  git push --tag || true

            - name: Read changelog
              id: read_changelog
              uses: mindsers/changelog-reader-action@v2
              with:
                  version: ${{ env.VERSION }}

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ env.TAG_NAME }}
                  draft: false
                  body: |
                      ## ${{ steps.read_changelog.outputs.version }} - ${{ steps.read_changelog.outputs.date }}

                      ${{ steps.read_changelog.outputs.changes }}
                  files: ${{ steps.download_release.outputs.file_path }}
