name: Release

on:
    repository_dispatch:
        types: [auto-generate-release]

jobs:
    run-on-dispatch:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Read version
              id: read_version
              shell: bash
              run: |
                  echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT

            - name: Checkout Auto.dn repo
              uses: actions/checkout@v4
              with:
                  repository: AuTsing/denofa
                  ref: refs/tags/v${{ steps.read_version.outputs.version }}
                  path: tmp/denofa
                  token: ${{ secrets.DENOFA_TOKEN }}

            - name: Copy files
              run: |
                  cp tmp/denofa/CHANGELOG.md ./CHANGELOG.md

            - name: Commit changes
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add .
                  git commit -m "${{ steps.read_version.outputs.version }}"
                  git push
                  git tag -d "v${{ steps.read_version.outputs.version }}"
                  git push origin --delete "v${{ steps.read_version.outputs.version }}"
                  git push --tag

            - name: Read changelog
              id: read_changelog
              uses: mindsers/changelog-reader-action@v2
              with:
                  version: ${{ steps.read_version.outputs.version }}

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  body: |
                      ## ${{ steps.read_changelog.outputs.version }} - ${{ steps.read_changelog.outputs.date }}

                      ${{ steps.read_changelog.outputs.changes }}
