name: Release

on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup nodejs
              uses: actions/setup-node@v6
              with:
                  node-version: 22

            - name: Download
              id: download
              env:
                  TAG: ${{ github.ref_name }}
                  TOKEN: ${{ secrets.AUTODN_TOKEN }}
              run: |
                  npm i @actions/core
                  node scripts/download.js

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  draft: false
                  files: ${{ steps.download.outputs.files }}
                  body: ${{ steps.download.outputs.body }}
